### ISSUE TITLE
TypeError: Object [object Object] has no method 'en'

### ISSUE THREAD

**Issue by bergerd1** [TelescopeJS/sample-project#14]
Not sure where to start with debugging this.  Any suggestions?
```
Now using node v0.10.41
Found package.json: ./bundle/programs/server/package.json
Running command: npm start

> meteor-dev-bundle@0.0.0 start /mnt/app/bundle/programs/server
> node ../../main

Kadira: completed instrumenting the app
!!! Found incomplete migration "addSlugsToPosts", removing and running again.
//----------------------------------------------------------------------//
//------------//    Starting addSlugsToPosts Migration    //-----------//
//----------------------------------------------------------------------//
Post: eHQx2jKw5h5hNdTdw | read-this-first
Warning: language en is not supported in this project, fallback language (en)

/mnt/app/bundle/programs/server/node_modules/fibers/future.js:267
						throw(ex);
						      ^
TypeError: Object [object Object] has no method 'en'
    at [object Object].__ (packages/tap_i18n/lib/tap_i18n/tap_i18n-server.coffee:29:16)
    at Object.i18n.t (packages/telescope:i18n/i18n.js:37:20)
    at Object.schema.(anonymous function).label (packages/telescope:i18n/i18n.js:52:21)
    at packages/aldeed_simple-schema.js:1811:31
    at Function._.each._.forEach (packages/underscore.js:142:22)
    at [object Object].SimpleSchema.getDefinition (packages/aldeed_simple-schema.js:1809:5)
    at checkObj (packages/aldeed_simple-schema.js:2391:16)
    at packages/aldeed_simple-schema.js:2487:11
    at Function._.each._.forEach (packages/underscore.js:147:22)
    at packages/aldeed_simple-schema.js:2479:11
```

**Comment by m0atz** [comment]
Same here, frustrating this one as it doesnt give much to go off.

**Comment by SachaG** [comment]
If you're using the latest version (Nova) this shouldn't happen, as it doesn't currently support internationalization.

**Comment by m0atz** [comment]
nice - thanks! seems i was using an old link to the legacy repo. migrating now :)

**Comment by zeronug** [comment]
I'm using the latest repo and it's still giving me this error.  I can't get past it.

**Comment by zeronug** [comment]
I git cloned the nova branch and I'm still getting the (en) error.  

`I20160503-20:44:13.228(0)? Kadira: completed instrumenting the app
I20160503-20:44:13.231(0)? Warning: language en is not supported in this project, fallback language (en)
W20160503-20:44:13.232(0)? (STDERR)
W20160503-20:44:13.233(0)? (STDERR) /root/.meteor/packages/meteor-tool/.1.3.2_4.10vjklo++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160503-20:44:13.233(0)? (STDERR)                                             throw(ex);
W20160503-20:44:13.234(0)? (STDERR)                                                   ^
W20160503-20:44:13.234(0)? (STDERR) TypeError: Object [object Object] has no method 'en'
W20160503-20:44:13.235(0)? (STDERR)     at [object Object].__ (packages/tap_i18n/lib/tap_i18n/tap_i18n-server.coffee:29:16)
W20160503-20:44:13.237(0)? (STDERR)     at Object.i18n.t (packages/telescope:i18n/i18n.js:37:20)
W20160503-20:44:13.238(0)? (STDERR)     at Object.schema.(anonymous function).label (packages/telescope:i18n/i18n.js:52:21)
W20160503-20:44:13.238(0)? (STDERR)     at packages/aldeed_simple-schema/simple-schema.js:839:1
W20160503-20:44:13.238(0)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:108:1)
W20160503-20:44:13.239(0)? (STDERR)     at [object Object].SimpleSchema.getDefinition (packages/aldeed_simple-schema/simple-schema.js:837:1)
W20160503-20:44:13.239(0)? (STDERR)     at checkObj (packages/aldeed_simple-schema/simple-schema-validation.js:217:1)
W20160503-20:44:13.239(0)? (STDERR)     at packages/aldeed_simple-schema/simple-schema-validation.js:262:1
W20160503-20:44:13.240(0)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:108:1)
W20160503-20:44:13.240(0)? (STDERR)     at checkObj (packages/aldeed_simple-schema/simple-schema-validation.js:261:1)
=> Exited with code: 8
I20160503-20:44:44.978(0)? Kadira: completed instrumenting the app
I20160503-20:44:45.000(0)? Warning: language en is not supported in this project, fallback language (en)
W20160503-20:44:45.001(0)? (STDERR)
W20160503-20:44:45.001(0)? (STDERR) /root/.meteor/packages/meteor-tool/.1.3.2_4.10vjklo++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160503-20:44:45.002(0)? (STDERR)                                             throw(ex);
W20160503-20:44:45.002(0)? (STDERR)                                                   ^
W20160503-20:44:45.118(0)? (STDERR) TypeError: Object [object Object] has no method 'en'
W20160503-20:44:45.118(0)? (STDERR)     at [object Object].__ (packages/tap_i18n/lib/tap_i18n/tap_i18n-server.coffee:29:16)
W20160503-20:44:45.118(0)? (STDERR)     at Object.i18n.t (packages/telescope:i18n/i18n.js:37:20)
W20160503-20:44:45.119(0)? (STDERR)     at Object.schema.(anonymous function).label (packages/telescope:i18n/i18n.js:52:21)
W20160503-20:44:45.121(0)? (STDERR)     at packages/aldeed_simple-schema/simple-schema.js:839:1
W20160503-20:44:45.121(0)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:108:1)
W20160503-20:44:45.121(0)? (STDERR)     at [object Object].SimpleSchema.getDefinition (packages/aldeed_simple-schema/simple-schema.js:837:1)
W20160503-20:44:45.122(0)? (STDERR)     at checkObj (packages/aldeed_simple-schema/simple-schema-validation.js:217:1)
W20160503-20:44:45.122(0)? (STDERR)     at packages/aldeed_simple-schema/simple-schema-validation.js:262:1
W20160503-20:44:45.122(0)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:108:1)
W20160503-20:44:45.122(0)? (STDERR)     at checkObj (packages/aldeed_simple-schema/simple-schema-validation.js:261:1)
=> Exited with code: 8
I20160503-20:45:05.751(0)? Kadira: completed instrumenting the app
I20160503-20:45:05.763(0)? Warning: language en is not supported in this project, fallback language (en)
W20160503-20:45:05.764(0)? (STDERR)
W20160503-20:45:05.764(0)? (STDERR) /root/.meteor/packages/meteor-tool/.1.3.2_4.10vjklo++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160503-20:45:05.764(0)? (STDERR)                                             throw(ex);
W20160503-20:45:05.765(0)? (STDERR)                                                   ^
W20160503-20:45:05.870(0)? (STDERR) TypeError: Object [object Object] has no method 'en'
W20160503-20:45:05.870(0)? (STDERR)     at [object Object].__ (packages/tap_i18n/lib/tap_i18n/tap_i18n-server.coffee:29:16)
W20160503-20:45:05.870(0)? (STDERR)     at Object.i18n.t (packages/telescope:i18n/i18n.js:37:20)
W20160503-20:45:05.870(0)? (STDERR)     at Object.schema.(anonymous function).label (packages/telescope:i18n/i18n.js:52:21)
W20160503-20:45:05.870(0)? (STDERR)     at packages/aldeed_simple-schema/simple-schema.js:839:1
W20160503-20:45:05.871(0)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:108:1)
W20160503-20:45:05.871(0)? (STDERR)     at [object Object].SimpleSchema.getDefinition (packages/aldeed_simple-schema/simple-schema.js:837:1)
W20160503-20:45:05.871(0)? (STDERR)     at checkObj (packages/aldeed_simple-schema/simple-schema-validation.js:217:1)
W20160503-20:45:05.871(0)? (STDERR)     at packages/aldeed_simple-schema/simple-schema-validation.js:262:1
W20160503-20:45:05.871(0)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:108:1)
W20160503-20:45:05.871(0)? (STDERR)     at checkObj (packages/aldeed_simple-schema/simple-schema-validation.js:261:1)
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
`

**Comment by SachaG** [comment]
@zeronug which repo/branch are you talking about exactly? What happens if you clone the master branch of this current repo?

**Comment by zeronug** [comment]
The master branch.  I didn't try it with the sample-project repo.

**Comment by zeronug** [comment]
I also tried the https://github.com/TelescopeJS/Telescope master branch the other day and had the same issue.

**Comment by SachaG** [comment]
In that case it's probably better to leave the issue in the repo where you're having the issue.

**Comment by zeronug** [comment]
No problem, I can do that.
