### ISSUE TITLE
mupx deploy Verifying deployment: FAILED

### ISSUE THREAD

**Issue by jujes** [TelescopeJS/sample-project#19]
how i can fix it?

```
Started TaskList: Deploy app 'meteor' (linux)
[192.168.10.10] - Uploading bundle
[192.168.10.10] - Uploading bundle: SUCCESS
[192.168.10.10] - Sending environment variables
[192.168.10.10] - Sending environment variables: SUCCESS
[192.168.10.10] - Initializing start script
[192.168.10.10] - Initializing start script: SUCCESS
[192.168.10.10] - Invoking deployment process
[192.168.10.10] - Invoking deployment process: SUCCESS
[192.168.10.10] - Verifying deployment
[192.168.10.10] x Verifying deployment: FAILED
	
	-----------------------------------STDERR-----------------------------------
	e?
	    at Object.Npm.require (/bundle/bundle/programs/server/boot.js:195:17)
	    at options.fallback (packages/modules-runtime/modules-runtime.js:21:1)
	    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:81:1)
	    at meteorInstall.node_modules.meteor.react-meteor-data.createContainer.jsx (packages/react-meteor-data/createContainer.jsx:5:1)
	    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
	    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
	    at meteorInstall.node_modules.meteor.react-meteor-data.react-meteor-data.jsx (packages/react-meteor-data/react-meteor-data.jsx:7:25)
	    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
	    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
	    at packages/react-meteor-data/createContainer.jsx:10:16
	 
	=> Redeploying previous version of the app
	 
	-----------------------------------STDOUT-----------------------------------
	
	To see more logs type 'mup logs --tail=50'
	
	----------------------------------------------------------------------------

```

**Comment by SachaG** [comment]
You can run `mupx logs -f` while you deploy to view the logs and get more info on the issue. Closing this as deployment issues are generally not related to Telescope itself.
