### ISSUE TITLE
Cannot read property 'ListContainer' of undefined

### ISSUE THREAD

**Issue by cikirt** [TelescopeJS/sample-project#21]
[root@iZ94v8enbj3Z sample-project]# meteor
[[[[[ /home/cikir/meteor/sample-project ]]]]] 

=> Started proxy.                             
=> Started MongoDB.                           
W20160614-10:39:32.788(8)? (STDERR)           
W20160614-10:39:32.790(8)? (STDERR) /root/.meteor/packages/meteor-tool/.1.3.2_4.10vjklo++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160614-10:39:32.790(8)? (STDERR)             				throw(ex);
W20160614-10:39:32.790(8)? (STDERR)             				      ^
W20160614-10:39:32.938(8)? (STDERR) TypeError: Cannot read property 'ListContainer' of undefined
W20160614-10:39:32.939(8)? (STDERR)     at meteorInstall.node_modules.meteor.nova:base-components.lib.common.Header.jsx (packages/nova:base-components/lib/common/Header.jsx:9:23)
W20160614-10:39:32.939(8)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
W20160614-10:39:32.939(8)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
W20160614-10:39:32.939(8)? (STDERR)     at meteorInstall.node_modules.meteor.nova:base-components.lib.components.js (packages/nova:base-components/lib/components.js:5:53)
W20160614-10:39:32.939(8)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
W20160614-10:39:32.940(8)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
W20160614-10:39:32.940(8)? (STDERR)     at /home/cikir/meteor/sample-project/.meteor/local/build/programs/server/packages/nova_base-components.js:5029:1
W20160614-10:39:32.940(8)? (STDERR)     at /home/cikir/meteor/sample-project/.meteor/local/build/programs/server/packages/nova_base-components.js:5036:3
W20160614-10:39:32.940(8)? (STDERR)     at /home/cikir/meteor/sample-project/.meteor/local/build/programs/server/boot.js:283:10
W20160614-10:39:32.941(8)? (STDERR)     at Array.forEach (native)
=> Exited with code: 8

**Comment by SachaG** [comment]
Sorry about that, use the main repo for now: https://github.com/TelescopeJS/Telescope/
